title: My Personal Portfolio
description: "A place for my diaries and notebooks"
theme: jekyll-theme-cayman  # or any of GitHub's built-in themes

collections:
  diary:
    output: true
    permalink: /diary/:title

